services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:80"
    restart: always
    environment:
      - NODE_ENV=production
      # Pass all VITE_ environment variables from host
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    # Mount volume for real-time env changes without rebuilding
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
