services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_DOCKER_BASE_URL=${VITE_DOCKER_BASE_URL}
    ports:
      - "8765:80"
    restart: always
    env_file:
      - .env
    # Mount volume for real-time env changes without rebuilding
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
