/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ValidateSessionImport } from './routes/validate-session'
import { Route as ComponentsImport } from './routes/components'
import { Route as R404Import } from './routes/404'
import { Route as R403Import } from './routes/403'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedVisitorManagementRouteImport } from './routes/_authenticated/visitor-management/route'
import { Route as AuthenticatedUserManagementRouteImport } from './routes/_authenticated/user-management/route'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules/route'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home/route'
import { Route as AuthenticatedEvacuationMonitoringRouteImport } from './routes/_authenticated/evacuation-monitoring/route'
import { Route as AuthenticatedDeviceManagementRouteImport } from './routes/_authenticated/device-management/route'
import { Route as AuthenticatedAttendanceMonitoringRouteImport } from './routes/_authenticated/attendance-monitoring/route'
import { Route as AuthenticatedVisitorManagementReportsImport } from './routes/_authenticated/visitor-management/reports'
import { Route as AuthenticatedUserManagementListOfUsersImport } from './routes/_authenticated/user-management/list-of-users'
import { Route as AuthenticatedEvacuationMonitoringReportsImport } from './routes/_authenticated/evacuation-monitoring/reports'
import { Route as AuthenticatedAttendanceMonitoringSettingsImport } from './routes/_authenticated/attendance-monitoring/settings'
import { Route as AuthenticatedAttendanceMonitoringReportsImport } from './routes/_authenticated/attendance-monitoring/reports'
import { Route as AuthenticatedAttendanceMonitoringEmployeesImport } from './routes/_authenticated/attendance-monitoring/employees'
import { Route as AuthenticatedEvacuationMonitoringCdeproIndexImport } from './routes/_authenticated/evacuation-monitoring/cdepro/index'
import { Route as AuthenticatedVisitorManagementReservedGuestRegisterGuestImport } from './routes/_authenticated/visitor-management/reserved-guest/register-guest'
import { Route as AuthenticatedVisitorManagementReservedGuestGuestListImport } from './routes/_authenticated/visitor-management/reserved-guest/guest-list'
import { Route as AuthenticatedVisitorManagementDashboardOverviewImport } from './routes/_authenticated/visitor-management/dashboard/overview'
import { Route as AuthenticatedVisitorManagementDashboardCheckInVisitorImport } from './routes/_authenticated/visitor-management/dashboard/check-in-visitor'
import { Route as AuthenticatedEvacuationMonitoringDashboardOverviewImport } from './routes/_authenticated/evacuation-monitoring/dashboard/overview'
import { Route as AuthenticatedDeviceManagementDashboardOverviewImport } from './routes/_authenticated/device-management/dashboard/overview'
import { Route as AuthenticatedDeviceManagementDashboardMappingImport } from './routes/_authenticated/device-management/dashboard/mapping'
import { Route as AuthenticatedAttendanceMonitoringDashboardOverviewImport } from './routes/_authenticated/attendance-monitoring/dashboard/overview'
import { Route as AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexImport } from './routes/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/index'
import { Route as AuthenticatedEvacuationMonitoringDashboardDivisionsIndexImport } from './routes/_authenticated/evacuation-monitoring/dashboard/divisions/index'
import { Route as AuthenticatedEvacuationMonitoringCdeproControllerIdIndexImport } from './routes/_authenticated/evacuation-monitoring/cdepro/$controllerId/index'
import { Route as AuthenticatedAttendanceMonitoringDashboardEntryExitIndexImport } from './routes/_authenticated/attendance-monitoring/dashboard/entry-exit/index'
import { Route as AuthenticatedAttendanceMonitoringDashboardDivisionsIndexImport } from './routes/_authenticated/attendance-monitoring/dashboard/divisions/index'
import { Route as AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexImport } from './routes/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/$deviceId/index'
import { Route as AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexImport } from './routes/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/index'
import { Route as AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexImport } from './routes/_authenticated/attendance-monitoring/dashboard/entry-exit/$deviceId/index'
import { Route as AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexImport } from './routes/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/index'
import { Route as AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexImport } from './routes/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/index'
import { Route as AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexImport } from './routes/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/index'
import { Route as AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexImport } from './routes/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/index'
import { Route as AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexImport } from './routes/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/index'

// Create/Update Routes

const ValidateSessionRoute = ValidateSessionImport.update({
  id: '/validate-session',
  path: '/validate-session',
  getParentRoute: () => rootRoute,
} as any)

const ComponentsRoute = ComponentsImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRoute,
} as any)

const R404Route = R404Import.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRoute,
} as any)

const R403Route = R403Import.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedVisitorManagementRouteRoute =
  AuthenticatedVisitorManagementRouteImport.update({
    id: '/visitor-management',
    path: '/visitor-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedUserManagementRouteRoute =
  AuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedModulesRouteRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedHomeRouteRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedEvacuationMonitoringRouteRoute =
  AuthenticatedEvacuationMonitoringRouteImport.update({
    id: '/evacuation-monitoring',
    path: '/evacuation-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedDeviceManagementRouteRoute =
  AuthenticatedDeviceManagementRouteImport.update({
    id: '/device-management',
    path: '/device-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringRouteRoute =
  AuthenticatedAttendanceMonitoringRouteImport.update({
    id: '/attendance-monitoring',
    path: '/attendance-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedVisitorManagementReportsRoute =
  AuthenticatedVisitorManagementReportsImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedVisitorManagementRouteRoute,
  } as any)

const AuthenticatedUserManagementListOfUsersRoute =
  AuthenticatedUserManagementListOfUsersImport.update({
    id: '/list-of-users',
    path: '/list-of-users',
    getParentRoute: () => AuthenticatedUserManagementRouteRoute,
  } as any)

const AuthenticatedEvacuationMonitoringReportsRoute =
  AuthenticatedEvacuationMonitoringReportsImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringSettingsRoute =
  AuthenticatedAttendanceMonitoringSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringReportsRoute =
  AuthenticatedAttendanceMonitoringReportsImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringEmployeesRoute =
  AuthenticatedAttendanceMonitoringEmployeesImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

const AuthenticatedEvacuationMonitoringCdeproIndexRoute =
  AuthenticatedEvacuationMonitoringCdeproIndexImport.update({
    id: '/cdepro/',
    path: '/cdepro/',
    getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
  } as any)

const AuthenticatedVisitorManagementReservedGuestRegisterGuestRoute =
  AuthenticatedVisitorManagementReservedGuestRegisterGuestImport.update({
    id: '/reserved-guest/register-guest',
    path: '/reserved-guest/register-guest',
    getParentRoute: () => AuthenticatedVisitorManagementRouteRoute,
  } as any)

const AuthenticatedVisitorManagementReservedGuestGuestListRoute =
  AuthenticatedVisitorManagementReservedGuestGuestListImport.update({
    id: '/reserved-guest/guest-list',
    path: '/reserved-guest/guest-list',
    getParentRoute: () => AuthenticatedVisitorManagementRouteRoute,
  } as any)

const AuthenticatedVisitorManagementDashboardOverviewRoute =
  AuthenticatedVisitorManagementDashboardOverviewImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => AuthenticatedVisitorManagementRouteRoute,
  } as any)

const AuthenticatedVisitorManagementDashboardCheckInVisitorRoute =
  AuthenticatedVisitorManagementDashboardCheckInVisitorImport.update({
    id: '/dashboard/check-in-visitor',
    path: '/dashboard/check-in-visitor',
    getParentRoute: () => AuthenticatedVisitorManagementRouteRoute,
  } as any)

const AuthenticatedEvacuationMonitoringDashboardOverviewRoute =
  AuthenticatedEvacuationMonitoringDashboardOverviewImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
  } as any)

const AuthenticatedDeviceManagementDashboardOverviewRoute =
  AuthenticatedDeviceManagementDashboardOverviewImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => AuthenticatedDeviceManagementRouteRoute,
  } as any)

const AuthenticatedDeviceManagementDashboardMappingRoute =
  AuthenticatedDeviceManagementDashboardMappingImport.update({
    id: '/dashboard/mapping',
    path: '/dashboard/mapping',
    getParentRoute: () => AuthenticatedDeviceManagementRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringDashboardOverviewRoute =
  AuthenticatedAttendanceMonitoringDashboardOverviewImport.update({
    id: '/dashboard/overview',
    path: '/dashboard/overview',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

const AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexRoute =
  AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexImport.update({
    id: '/dashboard/evacuation-exit/',
    path: '/dashboard/evacuation-exit/',
    getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
  } as any)

const AuthenticatedEvacuationMonitoringDashboardDivisionsIndexRoute =
  AuthenticatedEvacuationMonitoringDashboardDivisionsIndexImport.update({
    id: '/dashboard/divisions/',
    path: '/dashboard/divisions/',
    getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
  } as any)

const AuthenticatedEvacuationMonitoringCdeproControllerIdIndexRoute =
  AuthenticatedEvacuationMonitoringCdeproControllerIdIndexImport.update({
    id: '/cdepro/$controllerId/',
    path: '/cdepro/$controllerId/',
    getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringDashboardEntryExitIndexRoute =
  AuthenticatedAttendanceMonitoringDashboardEntryExitIndexImport.update({
    id: '/dashboard/entry-exit/',
    path: '/dashboard/entry-exit/',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

const AuthenticatedAttendanceMonitoringDashboardDivisionsIndexRoute =
  AuthenticatedAttendanceMonitoringDashboardDivisionsIndexImport.update({
    id: '/dashboard/divisions/',
    path: '/dashboard/divisions/',
    getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
  } as any)

const AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexRoute =
  AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexImport.update(
    {
      id: '/dashboard/evacuation-exit/$deviceId/',
      path: '/dashboard/evacuation-exit/$deviceId/',
      getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
    } as any,
  )

const AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexRoute =
  AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexImport.update(
    {
      id: '/dashboard/divisions/$divisionId/',
      path: '/dashboard/divisions/$divisionId/',
      getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
    } as any,
  )

const AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexRoute =
  AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexImport.update(
    {
      id: '/dashboard/entry-exit/$deviceId/',
      path: '/dashboard/entry-exit/$deviceId/',
      getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
    } as any,
  )

const AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexRoute =
  AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexImport.update(
    {
      id: '/dashboard/divisions/$divisionId/',
      path: '/dashboard/divisions/$divisionId/',
      getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
    } as any,
  )

const AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute =
  AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexImport.update(
    {
      id: '/dashboard/divisions/$divisionId/$departmentId/',
      path: '/dashboard/divisions/$divisionId/$departmentId/',
      getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
    } as any,
  )

const AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute =
  AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexImport.update(
    {
      id: '/dashboard/divisions/$divisionId/$departmentId/',
      path: '/dashboard/divisions/$divisionId/$departmentId/',
      getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
    } as any,
  )

const AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute =
  AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexImport.update(
    {
      id: '/dashboard/divisions/$divisionId/$departmentId/$sectionId/',
      path: '/dashboard/divisions/$divisionId/$departmentId/$sectionId/',
      getParentRoute: () => AuthenticatedEvacuationMonitoringRouteRoute,
    } as any,
  )

const AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute =
  AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexImport.update(
    {
      id: '/dashboard/divisions/$divisionId/$departmentId/$sectionId/',
      path: '/dashboard/divisions/$divisionId/$departmentId/$sectionId/',
      getParentRoute: () => AuthenticatedAttendanceMonitoringRouteRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403Import
      parentRoute: typeof rootRoute
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404Import
      parentRoute: typeof rootRoute
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsImport
      parentRoute: typeof rootRoute
    }
    '/validate-session': {
      id: '/validate-session'
      path: '/validate-session'
      fullPath: '/validate-session'
      preLoaderRoute: typeof ValidateSessionImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/attendance-monitoring': {
      id: '/_authenticated/attendance-monitoring'
      path: '/attendance-monitoring'
      fullPath: '/attendance-monitoring'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/device-management': {
      id: '/_authenticated/device-management'
      path: '/device-management'
      fullPath: '/device-management'
      preLoaderRoute: typeof AuthenticatedDeviceManagementRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/evacuation-monitoring': {
      id: '/_authenticated/evacuation-monitoring'
      path: '/evacuation-monitoring'
      fullPath: '/evacuation-monitoring'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/visitor-management': {
      id: '/_authenticated/visitor-management'
      path: '/visitor-management'
      fullPath: '/visitor-management'
      preLoaderRoute: typeof AuthenticatedVisitorManagementRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/attendance-monitoring/employees': {
      id: '/_authenticated/attendance-monitoring/employees'
      path: '/employees'
      fullPath: '/attendance-monitoring/employees'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringEmployeesImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/reports': {
      id: '/_authenticated/attendance-monitoring/reports'
      path: '/reports'
      fullPath: '/attendance-monitoring/reports'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringReportsImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/settings': {
      id: '/_authenticated/attendance-monitoring/settings'
      path: '/settings'
      fullPath: '/attendance-monitoring/settings'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringSettingsImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/evacuation-monitoring/reports': {
      id: '/_authenticated/evacuation-monitoring/reports'
      path: '/reports'
      fullPath: '/evacuation-monitoring/reports'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringReportsImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
    '/_authenticated/user-management/list-of-users': {
      id: '/_authenticated/user-management/list-of-users'
      path: '/list-of-users'
      fullPath: '/user-management/list-of-users'
      preLoaderRoute: typeof AuthenticatedUserManagementListOfUsersImport
      parentRoute: typeof AuthenticatedUserManagementRouteImport
    }
    '/_authenticated/visitor-management/reports': {
      id: '/_authenticated/visitor-management/reports'
      path: '/reports'
      fullPath: '/visitor-management/reports'
      preLoaderRoute: typeof AuthenticatedVisitorManagementReportsImport
      parentRoute: typeof AuthenticatedVisitorManagementRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/overview': {
      id: '/_authenticated/attendance-monitoring/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/attendance-monitoring/dashboard/overview'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardOverviewImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/device-management/dashboard/mapping': {
      id: '/_authenticated/device-management/dashboard/mapping'
      path: '/dashboard/mapping'
      fullPath: '/device-management/dashboard/mapping'
      preLoaderRoute: typeof AuthenticatedDeviceManagementDashboardMappingImport
      parentRoute: typeof AuthenticatedDeviceManagementRouteImport
    }
    '/_authenticated/device-management/dashboard/overview': {
      id: '/_authenticated/device-management/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/device-management/dashboard/overview'
      preLoaderRoute: typeof AuthenticatedDeviceManagementDashboardOverviewImport
      parentRoute: typeof AuthenticatedDeviceManagementRouteImport
    }
    '/_authenticated/evacuation-monitoring/dashboard/overview': {
      id: '/_authenticated/evacuation-monitoring/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/evacuation-monitoring/dashboard/overview'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringDashboardOverviewImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
    '/_authenticated/visitor-management/dashboard/check-in-visitor': {
      id: '/_authenticated/visitor-management/dashboard/check-in-visitor'
      path: '/dashboard/check-in-visitor'
      fullPath: '/visitor-management/dashboard/check-in-visitor'
      preLoaderRoute: typeof AuthenticatedVisitorManagementDashboardCheckInVisitorImport
      parentRoute: typeof AuthenticatedVisitorManagementRouteImport
    }
    '/_authenticated/visitor-management/dashboard/overview': {
      id: '/_authenticated/visitor-management/dashboard/overview'
      path: '/dashboard/overview'
      fullPath: '/visitor-management/dashboard/overview'
      preLoaderRoute: typeof AuthenticatedVisitorManagementDashboardOverviewImport
      parentRoute: typeof AuthenticatedVisitorManagementRouteImport
    }
    '/_authenticated/visitor-management/reserved-guest/guest-list': {
      id: '/_authenticated/visitor-management/reserved-guest/guest-list'
      path: '/reserved-guest/guest-list'
      fullPath: '/visitor-management/reserved-guest/guest-list'
      preLoaderRoute: typeof AuthenticatedVisitorManagementReservedGuestGuestListImport
      parentRoute: typeof AuthenticatedVisitorManagementRouteImport
    }
    '/_authenticated/visitor-management/reserved-guest/register-guest': {
      id: '/_authenticated/visitor-management/reserved-guest/register-guest'
      path: '/reserved-guest/register-guest'
      fullPath: '/visitor-management/reserved-guest/register-guest'
      preLoaderRoute: typeof AuthenticatedVisitorManagementReservedGuestRegisterGuestImport
      parentRoute: typeof AuthenticatedVisitorManagementRouteImport
    }
    '/_authenticated/evacuation-monitoring/cdepro/': {
      id: '/_authenticated/evacuation-monitoring/cdepro/'
      path: '/cdepro'
      fullPath: '/evacuation-monitoring/cdepro'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringCdeproIndexImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/divisions/': {
      id: '/_authenticated/attendance-monitoring/dashboard/divisions/'
      path: '/dashboard/divisions'
      fullPath: '/attendance-monitoring/dashboard/divisions'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardDivisionsIndexImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/entry-exit/': {
      id: '/_authenticated/attendance-monitoring/dashboard/entry-exit/'
      path: '/dashboard/entry-exit'
      fullPath: '/attendance-monitoring/dashboard/entry-exit'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardEntryExitIndexImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/evacuation-monitoring/cdepro/$controllerId/': {
      id: '/_authenticated/evacuation-monitoring/cdepro/$controllerId/'
      path: '/cdepro/$controllerId'
      fullPath: '/evacuation-monitoring/cdepro/$controllerId'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringCdeproControllerIdIndexImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
    '/_authenticated/evacuation-monitoring/dashboard/divisions/': {
      id: '/_authenticated/evacuation-monitoring/dashboard/divisions/'
      path: '/dashboard/divisions'
      fullPath: '/evacuation-monitoring/dashboard/divisions'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringDashboardDivisionsIndexImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
    '/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/': {
      id: '/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/'
      path: '/dashboard/evacuation-exit'
      fullPath: '/evacuation-monitoring/dashboard/evacuation-exit'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/': {
      id: '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/'
      path: '/dashboard/divisions/$divisionId'
      fullPath: '/attendance-monitoring/dashboard/divisions/$divisionId'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/entry-exit/$deviceId/': {
      id: '/_authenticated/attendance-monitoring/dashboard/entry-exit/$deviceId/'
      path: '/dashboard/entry-exit/$deviceId'
      fullPath: '/attendance-monitoring/dashboard/entry-exit/$deviceId'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/': {
      id: '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/'
      path: '/dashboard/divisions/$divisionId'
      fullPath: '/evacuation-monitoring/dashboard/divisions/$divisionId'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
    '/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/$deviceId/': {
      id: '/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/$deviceId/'
      path: '/dashboard/evacuation-exit/$deviceId'
      fullPath: '/evacuation-monitoring/dashboard/evacuation-exit/$deviceId'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/': {
      id: '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/'
      path: '/dashboard/divisions/$divisionId/$departmentId'
      fullPath: '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/': {
      id: '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/'
      path: '/dashboard/divisions/$divisionId/$departmentId'
      fullPath: '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
    '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/': {
      id: '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/'
      path: '/dashboard/divisions/$divisionId/$departmentId/$sectionId'
      fullPath: '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId'
      preLoaderRoute: typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexImport
      parentRoute: typeof AuthenticatedAttendanceMonitoringRouteImport
    }
    '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/': {
      id: '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/'
      path: '/dashboard/divisions/$divisionId/$departmentId/$sectionId'
      fullPath: '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId'
      preLoaderRoute: typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexImport
      parentRoute: typeof AuthenticatedEvacuationMonitoringRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedAttendanceMonitoringRouteRouteChildren {
  AuthenticatedAttendanceMonitoringEmployeesRoute: typeof AuthenticatedAttendanceMonitoringEmployeesRoute
  AuthenticatedAttendanceMonitoringReportsRoute: typeof AuthenticatedAttendanceMonitoringReportsRoute
  AuthenticatedAttendanceMonitoringSettingsRoute: typeof AuthenticatedAttendanceMonitoringSettingsRoute
  AuthenticatedAttendanceMonitoringDashboardOverviewRoute: typeof AuthenticatedAttendanceMonitoringDashboardOverviewRoute
  AuthenticatedAttendanceMonitoringDashboardDivisionsIndexRoute: typeof AuthenticatedAttendanceMonitoringDashboardDivisionsIndexRoute
  AuthenticatedAttendanceMonitoringDashboardEntryExitIndexRoute: typeof AuthenticatedAttendanceMonitoringDashboardEntryExitIndexRoute
  AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexRoute: typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexRoute
  AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexRoute: typeof AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexRoute
  AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute: typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute
  AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute: typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute
}

const AuthenticatedAttendanceMonitoringRouteRouteChildren: AuthenticatedAttendanceMonitoringRouteRouteChildren =
  {
    AuthenticatedAttendanceMonitoringEmployeesRoute:
      AuthenticatedAttendanceMonitoringEmployeesRoute,
    AuthenticatedAttendanceMonitoringReportsRoute:
      AuthenticatedAttendanceMonitoringReportsRoute,
    AuthenticatedAttendanceMonitoringSettingsRoute:
      AuthenticatedAttendanceMonitoringSettingsRoute,
    AuthenticatedAttendanceMonitoringDashboardOverviewRoute:
      AuthenticatedAttendanceMonitoringDashboardOverviewRoute,
    AuthenticatedAttendanceMonitoringDashboardDivisionsIndexRoute:
      AuthenticatedAttendanceMonitoringDashboardDivisionsIndexRoute,
    AuthenticatedAttendanceMonitoringDashboardEntryExitIndexRoute:
      AuthenticatedAttendanceMonitoringDashboardEntryExitIndexRoute,
    AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexRoute:
      AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexRoute,
    AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexRoute:
      AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexRoute,
    AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute:
      AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute,
    AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute:
      AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute,
  }

const AuthenticatedAttendanceMonitoringRouteRouteWithChildren =
  AuthenticatedAttendanceMonitoringRouteRoute._addFileChildren(
    AuthenticatedAttendanceMonitoringRouteRouteChildren,
  )

interface AuthenticatedDeviceManagementRouteRouteChildren {
  AuthenticatedDeviceManagementDashboardMappingRoute: typeof AuthenticatedDeviceManagementDashboardMappingRoute
  AuthenticatedDeviceManagementDashboardOverviewRoute: typeof AuthenticatedDeviceManagementDashboardOverviewRoute
}

const AuthenticatedDeviceManagementRouteRouteChildren: AuthenticatedDeviceManagementRouteRouteChildren =
  {
    AuthenticatedDeviceManagementDashboardMappingRoute:
      AuthenticatedDeviceManagementDashboardMappingRoute,
    AuthenticatedDeviceManagementDashboardOverviewRoute:
      AuthenticatedDeviceManagementDashboardOverviewRoute,
  }

const AuthenticatedDeviceManagementRouteRouteWithChildren =
  AuthenticatedDeviceManagementRouteRoute._addFileChildren(
    AuthenticatedDeviceManagementRouteRouteChildren,
  )

interface AuthenticatedEvacuationMonitoringRouteRouteChildren {
  AuthenticatedEvacuationMonitoringReportsRoute: typeof AuthenticatedEvacuationMonitoringReportsRoute
  AuthenticatedEvacuationMonitoringDashboardOverviewRoute: typeof AuthenticatedEvacuationMonitoringDashboardOverviewRoute
  AuthenticatedEvacuationMonitoringCdeproIndexRoute: typeof AuthenticatedEvacuationMonitoringCdeproIndexRoute
  AuthenticatedEvacuationMonitoringCdeproControllerIdIndexRoute: typeof AuthenticatedEvacuationMonitoringCdeproControllerIdIndexRoute
  AuthenticatedEvacuationMonitoringDashboardDivisionsIndexRoute: typeof AuthenticatedEvacuationMonitoringDashboardDivisionsIndexRoute
  AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexRoute: typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexRoute
  AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexRoute: typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexRoute
  AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexRoute: typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexRoute
  AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute: typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute
  AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute: typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute
}

const AuthenticatedEvacuationMonitoringRouteRouteChildren: AuthenticatedEvacuationMonitoringRouteRouteChildren =
  {
    AuthenticatedEvacuationMonitoringReportsRoute:
      AuthenticatedEvacuationMonitoringReportsRoute,
    AuthenticatedEvacuationMonitoringDashboardOverviewRoute:
      AuthenticatedEvacuationMonitoringDashboardOverviewRoute,
    AuthenticatedEvacuationMonitoringCdeproIndexRoute:
      AuthenticatedEvacuationMonitoringCdeproIndexRoute,
    AuthenticatedEvacuationMonitoringCdeproControllerIdIndexRoute:
      AuthenticatedEvacuationMonitoringCdeproControllerIdIndexRoute,
    AuthenticatedEvacuationMonitoringDashboardDivisionsIndexRoute:
      AuthenticatedEvacuationMonitoringDashboardDivisionsIndexRoute,
    AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexRoute:
      AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexRoute,
    AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexRoute:
      AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexRoute,
    AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexRoute:
      AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexRoute,
    AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute:
      AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute,
    AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute:
      AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute,
  }

const AuthenticatedEvacuationMonitoringRouteRouteWithChildren =
  AuthenticatedEvacuationMonitoringRouteRoute._addFileChildren(
    AuthenticatedEvacuationMonitoringRouteRouteChildren,
  )

interface AuthenticatedUserManagementRouteRouteChildren {
  AuthenticatedUserManagementListOfUsersRoute: typeof AuthenticatedUserManagementListOfUsersRoute
}

const AuthenticatedUserManagementRouteRouteChildren: AuthenticatedUserManagementRouteRouteChildren =
  {
    AuthenticatedUserManagementListOfUsersRoute:
      AuthenticatedUserManagementListOfUsersRoute,
  }

const AuthenticatedUserManagementRouteRouteWithChildren =
  AuthenticatedUserManagementRouteRoute._addFileChildren(
    AuthenticatedUserManagementRouteRouteChildren,
  )

interface AuthenticatedVisitorManagementRouteRouteChildren {
  AuthenticatedVisitorManagementReportsRoute: typeof AuthenticatedVisitorManagementReportsRoute
  AuthenticatedVisitorManagementDashboardCheckInVisitorRoute: typeof AuthenticatedVisitorManagementDashboardCheckInVisitorRoute
  AuthenticatedVisitorManagementDashboardOverviewRoute: typeof AuthenticatedVisitorManagementDashboardOverviewRoute
  AuthenticatedVisitorManagementReservedGuestGuestListRoute: typeof AuthenticatedVisitorManagementReservedGuestGuestListRoute
  AuthenticatedVisitorManagementReservedGuestRegisterGuestRoute: typeof AuthenticatedVisitorManagementReservedGuestRegisterGuestRoute
}

const AuthenticatedVisitorManagementRouteRouteChildren: AuthenticatedVisitorManagementRouteRouteChildren =
  {
    AuthenticatedVisitorManagementReportsRoute:
      AuthenticatedVisitorManagementReportsRoute,
    AuthenticatedVisitorManagementDashboardCheckInVisitorRoute:
      AuthenticatedVisitorManagementDashboardCheckInVisitorRoute,
    AuthenticatedVisitorManagementDashboardOverviewRoute:
      AuthenticatedVisitorManagementDashboardOverviewRoute,
    AuthenticatedVisitorManagementReservedGuestGuestListRoute:
      AuthenticatedVisitorManagementReservedGuestGuestListRoute,
    AuthenticatedVisitorManagementReservedGuestRegisterGuestRoute:
      AuthenticatedVisitorManagementReservedGuestRegisterGuestRoute,
  }

const AuthenticatedVisitorManagementRouteRouteWithChildren =
  AuthenticatedVisitorManagementRouteRoute._addFileChildren(
    AuthenticatedVisitorManagementRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceMonitoringRouteRoute: typeof AuthenticatedAttendanceMonitoringRouteRouteWithChildren
  AuthenticatedDeviceManagementRouteRoute: typeof AuthenticatedDeviceManagementRouteRouteWithChildren
  AuthenticatedEvacuationMonitoringRouteRoute: typeof AuthenticatedEvacuationMonitoringRouteRouteWithChildren
  AuthenticatedHomeRouteRoute: typeof AuthenticatedHomeRouteRoute
  AuthenticatedModulesRouteRoute: typeof AuthenticatedModulesRouteRoute
  AuthenticatedUserManagementRouteRoute: typeof AuthenticatedUserManagementRouteRouteWithChildren
  AuthenticatedVisitorManagementRouteRoute: typeof AuthenticatedVisitorManagementRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceMonitoringRouteRoute:
    AuthenticatedAttendanceMonitoringRouteRouteWithChildren,
  AuthenticatedDeviceManagementRouteRoute:
    AuthenticatedDeviceManagementRouteRouteWithChildren,
  AuthenticatedEvacuationMonitoringRouteRoute:
    AuthenticatedEvacuationMonitoringRouteRouteWithChildren,
  AuthenticatedHomeRouteRoute: AuthenticatedHomeRouteRoute,
  AuthenticatedModulesRouteRoute: AuthenticatedModulesRouteRoute,
  AuthenticatedUserManagementRouteRoute:
    AuthenticatedUserManagementRouteRouteWithChildren,
  AuthenticatedVisitorManagementRouteRoute:
    AuthenticatedVisitorManagementRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/components': typeof ComponentsRoute
  '/validate-session': typeof ValidateSessionRoute
  '/attendance-monitoring': typeof AuthenticatedAttendanceMonitoringRouteRouteWithChildren
  '/device-management': typeof AuthenticatedDeviceManagementRouteRouteWithChildren
  '/evacuation-monitoring': typeof AuthenticatedEvacuationMonitoringRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRouteRoute
  '/modules': typeof AuthenticatedModulesRouteRoute
  '/user-management': typeof AuthenticatedUserManagementRouteRouteWithChildren
  '/visitor-management': typeof AuthenticatedVisitorManagementRouteRouteWithChildren
  '/attendance-monitoring/employees': typeof AuthenticatedAttendanceMonitoringEmployeesRoute
  '/attendance-monitoring/reports': typeof AuthenticatedAttendanceMonitoringReportsRoute
  '/attendance-monitoring/settings': typeof AuthenticatedAttendanceMonitoringSettingsRoute
  '/evacuation-monitoring/reports': typeof AuthenticatedEvacuationMonitoringReportsRoute
  '/user-management/list-of-users': typeof AuthenticatedUserManagementListOfUsersRoute
  '/visitor-management/reports': typeof AuthenticatedVisitorManagementReportsRoute
  '/attendance-monitoring/dashboard/overview': typeof AuthenticatedAttendanceMonitoringDashboardOverviewRoute
  '/device-management/dashboard/mapping': typeof AuthenticatedDeviceManagementDashboardMappingRoute
  '/device-management/dashboard/overview': typeof AuthenticatedDeviceManagementDashboardOverviewRoute
  '/evacuation-monitoring/dashboard/overview': typeof AuthenticatedEvacuationMonitoringDashboardOverviewRoute
  '/visitor-management/dashboard/check-in-visitor': typeof AuthenticatedVisitorManagementDashboardCheckInVisitorRoute
  '/visitor-management/dashboard/overview': typeof AuthenticatedVisitorManagementDashboardOverviewRoute
  '/visitor-management/reserved-guest/guest-list': typeof AuthenticatedVisitorManagementReservedGuestGuestListRoute
  '/visitor-management/reserved-guest/register-guest': typeof AuthenticatedVisitorManagementReservedGuestRegisterGuestRoute
  '/evacuation-monitoring/cdepro': typeof AuthenticatedEvacuationMonitoringCdeproIndexRoute
  '/attendance-monitoring/dashboard/divisions': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsIndexRoute
  '/attendance-monitoring/dashboard/entry-exit': typeof AuthenticatedAttendanceMonitoringDashboardEntryExitIndexRoute
  '/evacuation-monitoring/cdepro/$controllerId': typeof AuthenticatedEvacuationMonitoringCdeproControllerIdIndexRoute
  '/evacuation-monitoring/dashboard/divisions': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsIndexRoute
  '/evacuation-monitoring/dashboard/evacuation-exit': typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexRoute
  '/attendance-monitoring/dashboard/divisions/$divisionId': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexRoute
  '/attendance-monitoring/dashboard/entry-exit/$deviceId': typeof AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexRoute
  '/evacuation-monitoring/dashboard/divisions/$divisionId': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexRoute
  '/evacuation-monitoring/dashboard/evacuation-exit/$deviceId': typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexRoute
  '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute
  '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute
  '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute
  '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteRouteWithChildren
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/components': typeof ComponentsRoute
  '/validate-session': typeof ValidateSessionRoute
  '/attendance-monitoring': typeof AuthenticatedAttendanceMonitoringRouteRouteWithChildren
  '/device-management': typeof AuthenticatedDeviceManagementRouteRouteWithChildren
  '/evacuation-monitoring': typeof AuthenticatedEvacuationMonitoringRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRouteRoute
  '/modules': typeof AuthenticatedModulesRouteRoute
  '/user-management': typeof AuthenticatedUserManagementRouteRouteWithChildren
  '/visitor-management': typeof AuthenticatedVisitorManagementRouteRouteWithChildren
  '/attendance-monitoring/employees': typeof AuthenticatedAttendanceMonitoringEmployeesRoute
  '/attendance-monitoring/reports': typeof AuthenticatedAttendanceMonitoringReportsRoute
  '/attendance-monitoring/settings': typeof AuthenticatedAttendanceMonitoringSettingsRoute
  '/evacuation-monitoring/reports': typeof AuthenticatedEvacuationMonitoringReportsRoute
  '/user-management/list-of-users': typeof AuthenticatedUserManagementListOfUsersRoute
  '/visitor-management/reports': typeof AuthenticatedVisitorManagementReportsRoute
  '/attendance-monitoring/dashboard/overview': typeof AuthenticatedAttendanceMonitoringDashboardOverviewRoute
  '/device-management/dashboard/mapping': typeof AuthenticatedDeviceManagementDashboardMappingRoute
  '/device-management/dashboard/overview': typeof AuthenticatedDeviceManagementDashboardOverviewRoute
  '/evacuation-monitoring/dashboard/overview': typeof AuthenticatedEvacuationMonitoringDashboardOverviewRoute
  '/visitor-management/dashboard/check-in-visitor': typeof AuthenticatedVisitorManagementDashboardCheckInVisitorRoute
  '/visitor-management/dashboard/overview': typeof AuthenticatedVisitorManagementDashboardOverviewRoute
  '/visitor-management/reserved-guest/guest-list': typeof AuthenticatedVisitorManagementReservedGuestGuestListRoute
  '/visitor-management/reserved-guest/register-guest': typeof AuthenticatedVisitorManagementReservedGuestRegisterGuestRoute
  '/evacuation-monitoring/cdepro': typeof AuthenticatedEvacuationMonitoringCdeproIndexRoute
  '/attendance-monitoring/dashboard/divisions': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsIndexRoute
  '/attendance-monitoring/dashboard/entry-exit': typeof AuthenticatedAttendanceMonitoringDashboardEntryExitIndexRoute
  '/evacuation-monitoring/cdepro/$controllerId': typeof AuthenticatedEvacuationMonitoringCdeproControllerIdIndexRoute
  '/evacuation-monitoring/dashboard/divisions': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsIndexRoute
  '/evacuation-monitoring/dashboard/evacuation-exit': typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexRoute
  '/attendance-monitoring/dashboard/divisions/$divisionId': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexRoute
  '/attendance-monitoring/dashboard/entry-exit/$deviceId': typeof AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexRoute
  '/evacuation-monitoring/dashboard/divisions/$divisionId': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexRoute
  '/evacuation-monitoring/dashboard/evacuation-exit/$deviceId': typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexRoute
  '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute
  '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute
  '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute
  '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/components': typeof ComponentsRoute
  '/validate-session': typeof ValidateSessionRoute
  '/_authenticated/attendance-monitoring': typeof AuthenticatedAttendanceMonitoringRouteRouteWithChildren
  '/_authenticated/device-management': typeof AuthenticatedDeviceManagementRouteRouteWithChildren
  '/_authenticated/evacuation-monitoring': typeof AuthenticatedEvacuationMonitoringRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRouteRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRouteRoute
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRouteRouteWithChildren
  '/_authenticated/visitor-management': typeof AuthenticatedVisitorManagementRouteRouteWithChildren
  '/_authenticated/attendance-monitoring/employees': typeof AuthenticatedAttendanceMonitoringEmployeesRoute
  '/_authenticated/attendance-monitoring/reports': typeof AuthenticatedAttendanceMonitoringReportsRoute
  '/_authenticated/attendance-monitoring/settings': typeof AuthenticatedAttendanceMonitoringSettingsRoute
  '/_authenticated/evacuation-monitoring/reports': typeof AuthenticatedEvacuationMonitoringReportsRoute
  '/_authenticated/user-management/list-of-users': typeof AuthenticatedUserManagementListOfUsersRoute
  '/_authenticated/visitor-management/reports': typeof AuthenticatedVisitorManagementReportsRoute
  '/_authenticated/attendance-monitoring/dashboard/overview': typeof AuthenticatedAttendanceMonitoringDashboardOverviewRoute
  '/_authenticated/device-management/dashboard/mapping': typeof AuthenticatedDeviceManagementDashboardMappingRoute
  '/_authenticated/device-management/dashboard/overview': typeof AuthenticatedDeviceManagementDashboardOverviewRoute
  '/_authenticated/evacuation-monitoring/dashboard/overview': typeof AuthenticatedEvacuationMonitoringDashboardOverviewRoute
  '/_authenticated/visitor-management/dashboard/check-in-visitor': typeof AuthenticatedVisitorManagementDashboardCheckInVisitorRoute
  '/_authenticated/visitor-management/dashboard/overview': typeof AuthenticatedVisitorManagementDashboardOverviewRoute
  '/_authenticated/visitor-management/reserved-guest/guest-list': typeof AuthenticatedVisitorManagementReservedGuestGuestListRoute
  '/_authenticated/visitor-management/reserved-guest/register-guest': typeof AuthenticatedVisitorManagementReservedGuestRegisterGuestRoute
  '/_authenticated/evacuation-monitoring/cdepro/': typeof AuthenticatedEvacuationMonitoringCdeproIndexRoute
  '/_authenticated/attendance-monitoring/dashboard/divisions/': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsIndexRoute
  '/_authenticated/attendance-monitoring/dashboard/entry-exit/': typeof AuthenticatedAttendanceMonitoringDashboardEntryExitIndexRoute
  '/_authenticated/evacuation-monitoring/cdepro/$controllerId/': typeof AuthenticatedEvacuationMonitoringCdeproControllerIdIndexRoute
  '/_authenticated/evacuation-monitoring/dashboard/divisions/': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsIndexRoute
  '/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/': typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitIndexRoute
  '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdIndexRoute
  '/_authenticated/attendance-monitoring/dashboard/entry-exit/$deviceId/': typeof AuthenticatedAttendanceMonitoringDashboardEntryExitDeviceIdIndexRoute
  '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdIndexRoute
  '/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/$deviceId/': typeof AuthenticatedEvacuationMonitoringDashboardEvacuationExitDeviceIdIndexRoute
  '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute
  '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdIndexRoute
  '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/': typeof AuthenticatedAttendanceMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute
  '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/': typeof AuthenticatedEvacuationMonitoringDashboardDivisionsDivisionIdDepartmentIdSectionIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/403'
    | '/404'
    | '/components'
    | '/validate-session'
    | '/attendance-monitoring'
    | '/device-management'
    | '/evacuation-monitoring'
    | '/home'
    | '/modules'
    | '/user-management'
    | '/visitor-management'
    | '/attendance-monitoring/employees'
    | '/attendance-monitoring/reports'
    | '/attendance-monitoring/settings'
    | '/evacuation-monitoring/reports'
    | '/user-management/list-of-users'
    | '/visitor-management/reports'
    | '/attendance-monitoring/dashboard/overview'
    | '/device-management/dashboard/mapping'
    | '/device-management/dashboard/overview'
    | '/evacuation-monitoring/dashboard/overview'
    | '/visitor-management/dashboard/check-in-visitor'
    | '/visitor-management/dashboard/overview'
    | '/visitor-management/reserved-guest/guest-list'
    | '/visitor-management/reserved-guest/register-guest'
    | '/evacuation-monitoring/cdepro'
    | '/attendance-monitoring/dashboard/divisions'
    | '/attendance-monitoring/dashboard/entry-exit'
    | '/evacuation-monitoring/cdepro/$controllerId'
    | '/evacuation-monitoring/dashboard/divisions'
    | '/evacuation-monitoring/dashboard/evacuation-exit'
    | '/attendance-monitoring/dashboard/divisions/$divisionId'
    | '/attendance-monitoring/dashboard/entry-exit/$deviceId'
    | '/evacuation-monitoring/dashboard/divisions/$divisionId'
    | '/evacuation-monitoring/dashboard/evacuation-exit/$deviceId'
    | '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId'
    | '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId'
    | '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId'
    | '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/403'
    | '/404'
    | '/components'
    | '/validate-session'
    | '/attendance-monitoring'
    | '/device-management'
    | '/evacuation-monitoring'
    | '/home'
    | '/modules'
    | '/user-management'
    | '/visitor-management'
    | '/attendance-monitoring/employees'
    | '/attendance-monitoring/reports'
    | '/attendance-monitoring/settings'
    | '/evacuation-monitoring/reports'
    | '/user-management/list-of-users'
    | '/visitor-management/reports'
    | '/attendance-monitoring/dashboard/overview'
    | '/device-management/dashboard/mapping'
    | '/device-management/dashboard/overview'
    | '/evacuation-monitoring/dashboard/overview'
    | '/visitor-management/dashboard/check-in-visitor'
    | '/visitor-management/dashboard/overview'
    | '/visitor-management/reserved-guest/guest-list'
    | '/visitor-management/reserved-guest/register-guest'
    | '/evacuation-monitoring/cdepro'
    | '/attendance-monitoring/dashboard/divisions'
    | '/attendance-monitoring/dashboard/entry-exit'
    | '/evacuation-monitoring/cdepro/$controllerId'
    | '/evacuation-monitoring/dashboard/divisions'
    | '/evacuation-monitoring/dashboard/evacuation-exit'
    | '/attendance-monitoring/dashboard/divisions/$divisionId'
    | '/attendance-monitoring/dashboard/entry-exit/$deviceId'
    | '/evacuation-monitoring/dashboard/divisions/$divisionId'
    | '/evacuation-monitoring/dashboard/evacuation-exit/$deviceId'
    | '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId'
    | '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId'
    | '/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId'
    | '/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/403'
    | '/404'
    | '/components'
    | '/validate-session'
    | '/_authenticated/attendance-monitoring'
    | '/_authenticated/device-management'
    | '/_authenticated/evacuation-monitoring'
    | '/_authenticated/home'
    | '/_authenticated/modules'
    | '/_authenticated/user-management'
    | '/_authenticated/visitor-management'
    | '/_authenticated/attendance-monitoring/employees'
    | '/_authenticated/attendance-monitoring/reports'
    | '/_authenticated/attendance-monitoring/settings'
    | '/_authenticated/evacuation-monitoring/reports'
    | '/_authenticated/user-management/list-of-users'
    | '/_authenticated/visitor-management/reports'
    | '/_authenticated/attendance-monitoring/dashboard/overview'
    | '/_authenticated/device-management/dashboard/mapping'
    | '/_authenticated/device-management/dashboard/overview'
    | '/_authenticated/evacuation-monitoring/dashboard/overview'
    | '/_authenticated/visitor-management/dashboard/check-in-visitor'
    | '/_authenticated/visitor-management/dashboard/overview'
    | '/_authenticated/visitor-management/reserved-guest/guest-list'
    | '/_authenticated/visitor-management/reserved-guest/register-guest'
    | '/_authenticated/evacuation-monitoring/cdepro/'
    | '/_authenticated/attendance-monitoring/dashboard/divisions/'
    | '/_authenticated/attendance-monitoring/dashboard/entry-exit/'
    | '/_authenticated/evacuation-monitoring/cdepro/$controllerId/'
    | '/_authenticated/evacuation-monitoring/dashboard/divisions/'
    | '/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/'
    | '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/'
    | '/_authenticated/attendance-monitoring/dashboard/entry-exit/$deviceId/'
    | '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/'
    | '/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/$deviceId/'
    | '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/'
    | '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/'
    | '/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/'
    | '/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  ComponentsRoute: typeof ComponentsRoute
  ValidateSessionRoute: typeof ValidateSessionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R403Route: R403Route,
  R404Route: R404Route,
  ComponentsRoute: ComponentsRoute,
  ValidateSessionRoute: ValidateSessionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/403",
        "/404",
        "/components",
        "/validate-session"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/attendance-monitoring",
        "/_authenticated/device-management",
        "/_authenticated/evacuation-monitoring",
        "/_authenticated/home",
        "/_authenticated/modules",
        "/_authenticated/user-management",
        "/_authenticated/visitor-management"
      ]
    },
    "/403": {
      "filePath": "403.tsx"
    },
    "/404": {
      "filePath": "404.tsx"
    },
    "/components": {
      "filePath": "components.tsx"
    },
    "/validate-session": {
      "filePath": "validate-session.tsx"
    },
    "/_authenticated/attendance-monitoring": {
      "filePath": "_authenticated/attendance-monitoring/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/attendance-monitoring/employees",
        "/_authenticated/attendance-monitoring/reports",
        "/_authenticated/attendance-monitoring/settings",
        "/_authenticated/attendance-monitoring/dashboard/overview",
        "/_authenticated/attendance-monitoring/dashboard/divisions/",
        "/_authenticated/attendance-monitoring/dashboard/entry-exit/",
        "/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/",
        "/_authenticated/attendance-monitoring/dashboard/entry-exit/$deviceId/",
        "/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/",
        "/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/"
      ]
    },
    "/_authenticated/device-management": {
      "filePath": "_authenticated/device-management/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/device-management/dashboard/mapping",
        "/_authenticated/device-management/dashboard/overview"
      ]
    },
    "/_authenticated/evacuation-monitoring": {
      "filePath": "_authenticated/evacuation-monitoring/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/evacuation-monitoring/reports",
        "/_authenticated/evacuation-monitoring/dashboard/overview",
        "/_authenticated/evacuation-monitoring/cdepro/",
        "/_authenticated/evacuation-monitoring/cdepro/$controllerId/",
        "/_authenticated/evacuation-monitoring/dashboard/divisions/",
        "/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/",
        "/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/",
        "/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/$deviceId/",
        "/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/",
        "/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/"
      ]
    },
    "/_authenticated/home": {
      "filePath": "_authenticated/home/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/modules": {
      "filePath": "_authenticated/modules/route.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/user-management": {
      "filePath": "_authenticated/user-management/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/user-management/list-of-users"
      ]
    },
    "/_authenticated/visitor-management": {
      "filePath": "_authenticated/visitor-management/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/visitor-management/reports",
        "/_authenticated/visitor-management/dashboard/check-in-visitor",
        "/_authenticated/visitor-management/dashboard/overview",
        "/_authenticated/visitor-management/reserved-guest/guest-list",
        "/_authenticated/visitor-management/reserved-guest/register-guest"
      ]
    },
    "/_authenticated/attendance-monitoring/employees": {
      "filePath": "_authenticated/attendance-monitoring/employees.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/attendance-monitoring/reports": {
      "filePath": "_authenticated/attendance-monitoring/reports.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/attendance-monitoring/settings": {
      "filePath": "_authenticated/attendance-monitoring/settings.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/evacuation-monitoring/reports": {
      "filePath": "_authenticated/evacuation-monitoring/reports.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    },
    "/_authenticated/user-management/list-of-users": {
      "filePath": "_authenticated/user-management/list-of-users.tsx",
      "parent": "/_authenticated/user-management"
    },
    "/_authenticated/visitor-management/reports": {
      "filePath": "_authenticated/visitor-management/reports.tsx",
      "parent": "/_authenticated/visitor-management"
    },
    "/_authenticated/attendance-monitoring/dashboard/overview": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/overview.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/device-management/dashboard/mapping": {
      "filePath": "_authenticated/device-management/dashboard/mapping.tsx",
      "parent": "/_authenticated/device-management"
    },
    "/_authenticated/device-management/dashboard/overview": {
      "filePath": "_authenticated/device-management/dashboard/overview.tsx",
      "parent": "/_authenticated/device-management"
    },
    "/_authenticated/evacuation-monitoring/dashboard/overview": {
      "filePath": "_authenticated/evacuation-monitoring/dashboard/overview.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    },
    "/_authenticated/visitor-management/dashboard/check-in-visitor": {
      "filePath": "_authenticated/visitor-management/dashboard/check-in-visitor.tsx",
      "parent": "/_authenticated/visitor-management"
    },
    "/_authenticated/visitor-management/dashboard/overview": {
      "filePath": "_authenticated/visitor-management/dashboard/overview.tsx",
      "parent": "/_authenticated/visitor-management"
    },
    "/_authenticated/visitor-management/reserved-guest/guest-list": {
      "filePath": "_authenticated/visitor-management/reserved-guest/guest-list.tsx",
      "parent": "/_authenticated/visitor-management"
    },
    "/_authenticated/visitor-management/reserved-guest/register-guest": {
      "filePath": "_authenticated/visitor-management/reserved-guest/register-guest.tsx",
      "parent": "/_authenticated/visitor-management"
    },
    "/_authenticated/evacuation-monitoring/cdepro/": {
      "filePath": "_authenticated/evacuation-monitoring/cdepro/index.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    },
    "/_authenticated/attendance-monitoring/dashboard/divisions/": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/divisions/index.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/attendance-monitoring/dashboard/entry-exit/": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/entry-exit/index.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/evacuation-monitoring/cdepro/$controllerId/": {
      "filePath": "_authenticated/evacuation-monitoring/cdepro/$controllerId/index.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    },
    "/_authenticated/evacuation-monitoring/dashboard/divisions/": {
      "filePath": "_authenticated/evacuation-monitoring/dashboard/divisions/index.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    },
    "/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/": {
      "filePath": "_authenticated/evacuation-monitoring/dashboard/evacuation-exit/index.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    },
    "/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/index.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/attendance-monitoring/dashboard/entry-exit/$deviceId/": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/entry-exit/$deviceId/index.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/": {
      "filePath": "_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/index.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    },
    "/_authenticated/evacuation-monitoring/dashboard/evacuation-exit/$deviceId/": {
      "filePath": "_authenticated/evacuation-monitoring/dashboard/evacuation-exit/$deviceId/index.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    },
    "/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/index.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/": {
      "filePath": "_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/index.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    },
    "/_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/": {
      "filePath": "_authenticated/attendance-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/index.tsx",
      "parent": "/_authenticated/attendance-monitoring"
    },
    "/_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/": {
      "filePath": "_authenticated/evacuation-monitoring/dashboard/divisions/$divisionId/$departmentId/$sectionId/index.tsx",
      "parent": "/_authenticated/evacuation-monitoring"
    }
  }
}
ROUTE_MANIFEST_END */
