/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ComponentsImport } from './routes/components'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AuthenticatedAttendancemonitoringDashboardIndexImport } from './routes/_authenticated/attendance_monitoring/dashboard/index'

// Create/Update Routes

const ComponentsRoute = ComponentsImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAttendancemonitoringDashboardIndexRoute =
  AuthenticatedAttendancemonitoringDashboardIndexImport.update({
    id: '/_authenticated/attendance_monitoring/dashboard/',
    path: '/attendance_monitoring/dashboard/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/attendance_monitoring/dashboard/': {
      id: '/_authenticated/attendance_monitoring/dashboard/'
      path: '/attendance_monitoring/dashboard'
      fullPath: '/attendance_monitoring/dashboard'
      preLoaderRoute: typeof AuthenticatedAttendancemonitoringDashboardIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/attendance_monitoring/dashboard': typeof AuthenticatedAttendancemonitoringDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/attendance_monitoring/dashboard': typeof AuthenticatedAttendancemonitoringDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_authenticated/attendance_monitoring/dashboard/': typeof AuthenticatedAttendancemonitoringDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/dashboard'
    | '/attendance_monitoring/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components' | '/dashboard' | '/attendance_monitoring/dashboard'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/dashboard/'
    | '/_authenticated/attendance_monitoring/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AuthenticatedAttendancemonitoringDashboardIndexRoute: typeof AuthenticatedAttendancemonitoringDashboardIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AuthenticatedAttendancemonitoringDashboardIndexRoute:
    AuthenticatedAttendancemonitoringDashboardIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/components",
        "/dashboard/",
        "/_authenticated/attendance_monitoring/dashboard/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/components": {
      "filePath": "components.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/_authenticated/attendance_monitoring/dashboard/": {
      "filePath": "_authenticated/attendance_monitoring/dashboard/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
